name: Cache Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at midnight

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Cleanup Cache
        run: |
          gh extension install actions/gh-actions-cache
          
          REPO=${{ github.repository }}
          BRANCH="refs/heads/main"
          
          echo "Fetching list of cache keys..."
          cacheKeys=$(gh actions-cache list -R $REPO -B $BRANCH | cut -f 1 )
          
          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeys
          do
              gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
          done
          echo "Done cleaning up caches."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
